# Generated by Django 4.1.1 on 2022-09-24 17:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_code',
            field=models.CharField(default=authentication.models.generate_random_code, max_length=10, null=True),
        ),
    ]
