# Generated by Django 4.1.1 on 2022-09-24 18:08

from authentication.models import generate_random_code
from django.db import migrations


def generate_short_code_for_users(apps, _):
    User = apps.get_model('authentication', 'User')
    for user in User.objects.all():
        user.short_code = generate_random_code()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_short_code'),
    ]

    operations = [
        migrations.RunPython(generate_short_code_for_users)
    ]
