# Generated by Django 4.1.1 on 2022-09-24 18:09

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_populate_user_short_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_code',
            field=models.CharField(default=authentication.models.generate_random_code, max_length=10, unique=True),
        ),
    ]
