# Generated by Django 4.1.1 on 2022-09-09 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filesystem.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesystemItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('filesize', models.PositiveBigIntegerField(default=0)),
                ('is_file', models.BooleanField()),
                ('uploaded_file', models.FileField(upload_to=filesystem.models.user_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesystem.filesystemitem')),
            ],
        ),
    ]
