# Generated by Django 4.1.1 on 2022-09-09 12:22

from django.db import migrations, models
import filesystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=filesystem.models.user_directory_path),
        ),
    ]
