# Generated by Django 4.1.1 on 2022-09-12 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_alter_filesystemitem_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystemitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesystemitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
