# Generated by Django 4.1.1 on 2022-09-23 09:57

from django.db import migrations, models

DEFAULT = '/'

def forwards(apps, _):
	FilesystemItem = apps.get_model('filesystem', 'FilesystemItem')
	filesytemitems = FilesystemItem.objects.all()
	for item in filesytemitems:
			path = ''
			if item.parent is not None:
				parent = item.parent
				while (parent is not None):
					path = '/' + parent.name + path
					parent = parent.parent
			path += '/' + item.name
			item.path = path
			item.save()

def backwards(apps, _):
	FilesystemItem = apps.get_model('filesystem', 'FilesystemItem')
	filesytemitems = FilesystemItem.objects.all()
	for item in filesytemitems:
		item.path = DEFAULT
		item.save()

class Migration(migrations.Migration):

	dependencies = [
		('filesystem', '0004_filesystemitem_allow_any'),
	]

	operations = [
		migrations.AddField(
			model_name='filesystemitem',
			name='path',
			field=models.CharField(default=DEFAULT, max_length=4096),
			preserve_default=False,
		),
		migrations.RunPython(forwards, backwards)
	]
