# Generated by Django 4.1.1 on 2022-09-24 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesystem', '0006_filesystemshareditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystemshareditem',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
