# Generated by Django 4.1.1 on 2022-09-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0007_alter_filesystemshareditem_allowed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesystemitem',
            name='allow_any',
        ),
    ]
